package ilya.khrushchev.testmultymodule.di

import dagger.Binds
import dagger.Module
import ilya.khrushchev.firstfeature.navigation.FirstFeatureNavCommandProvider
import ilya.khrushchev.testmultymodule.navigation.FirstFeatureNavCommandProviderImpl

